import { AlertCircle, CheckCircle2, ChevronDown, LoaderCircle, MoreHorizontal, Search, X } from 'lucide-react'
import { useState } from 'react'

export function Button({ children, variant='primary', className='', icon:Icon, ...props }) { const styles={primary:'bg-msu-700 text-white hover:bg-msu-800',secondary:'border bg-white text-slate-700 hover:bg-slate-50',danger:'bg-red-600 text-white hover:bg-red-700',ghost:'text-slate-600 hover:bg-slate-100'}; return <button className={`inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props}>{Icon && <Icon size={16}/>} {children}</button> }
export function Badge({ children }) { const v={Waiting:'bg-amber-50 text-amber-700',Called:'bg-blue-50 text-blue-700','Now Serving':'bg-msu-50 text-msu-700',Confirmed:'bg-emerald-50 text-emerald-700',Completed:'bg-slate-100 text-slate-600',Pending:'bg-violet-50 text-violet-700',Active:'bg-emerald-50 text-emerald-700',Skipped:'bg-red-50 text-red-700',Cancelled:'bg-red-50 text-red-700',Missed:'bg-orange-50 text-orange-700','Checked in':'bg-blue-50 text-blue-700'}; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${v[children]||'bg-slate-100 text-slate-600'}`}>{children}</span> }
export function Card({children,className=''}) { return <section className={`card ${className}`}>{children}</section> }
export function Metric({label,value,note,icon:Icon,tone='green'}) { const c={green:'bg-msu-50 text-msu-700',blue:'bg-blue-50 text-blue-700',amber:'bg-amber-50 text-amber-700',purple:'bg-purple-50 text-purple-700'}; return <Card className="p-4"><div className="flex items-start justify-between"><div><p className="muted">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div><span className={`rounded-lg p-2.5 ${c[tone]}`}><Icon size={20}/></span></div></Card> }
export function DataTable({columns, rows}) { return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{columns.map(c=><th key={c} className="px-4 py-3 font-semibold">{c}</th>)}</tr></thead><tbody className="divide-y">{rows}</tbody></table></div> }
export function SearchInput() { return <div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input className="input pl-9" placeholder="Search..." /></div> }
export function EmptyState({title='No records found',text='There is nothing to show here yet.'}) { return <div className="p-10 text-center"><AlertCircle className="mx-auto text-slate-300" size={34}/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div> }
export function LoadingState() { return <div className="flex items-center justify-center gap-2 p-10 text-sm text-slate-500"><LoaderCircle className="animate-spin" size={18}/> Loading AQMS data…</div> }
export function Alert({children}) { return <div className="flex gap-3 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800"><CheckCircle2 size={18} className="shrink-0"/>{children}</div> }
export function Modal({open,onClose,title,children}) { if(!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold">{title}</h2><button onClick={onClose}><X size={20}/></button></div><div className="p-5">{children}</div></div></div> }
export function ConfirmDialog({open,onClose,onConfirm,title='Confirm action',message}) { return <Modal open={open} onClose={onClose} title={title}><p className="text-sm text-slate-600">{message}</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" onClick={()=>{onConfirm?.();onClose()}}>Confirm</Button></div></Modal> }
export function Dropdown({label='Actions',children}) { const [open,setOpen]=useState(false); return <div className="relative"><Button variant="secondary" icon={ChevronDown} onClick={()=>setOpen(!open)}>{label}</Button>{open&&<div className="absolute right-0 z-20 mt-1 w-44 rounded-lg border bg-white p-1 shadow-lg">{children}</div>}</div> }
export const ActionDots=()=> <button className="rounded p-1 text-slate-400 hover:bg-slate-100"><MoreHorizontal size={18}/></button>
